# Generated by Django 4.1 on 2023-10-17 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DayOfWeek',
            fields=[
                ('day_id', models.IntegerField(primary_key=True, serialize=False)),
                ('day_name', models.CharField(max_length=5)),
            ],
            options={
                'db_table': 'day_of_week',
            },
        ),
        migrations.CreateModel(
            name='Month',
            fields=[
                ('month_id', models.IntegerField(primary_key=True, serialize=False)),
                ('month', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Payroll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_name', models.CharField(max_length=20)),
                ('month', models.CharField(max_length=5)),
            ],
            options={
                'db_table': 'payroll',
            },
        ),
        migrations.CreateModel(
            name='RegisterLesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_name', models.CharField(max_length=20)),
                ('day_of_week', models.CharField(max_length=5)),
                ('student1_1', models.CharField(max_length=20, null=True)),
                ('student1_2', models.CharField(max_length=20, null=True)),
                ('student2_1', models.CharField(max_length=20, null=True)),
                ('student2_2', models.CharField(max_length=20, null=True)),
                ('student3_1', models.CharField(max_length=20, null=True)),
                ('student3_2', models.CharField(max_length=20, null=True)),
                ('student4_1', models.CharField(max_length=20, null=True)),
                ('student4_2', models.CharField(max_length=20, null=True)),
                ('class_time', models.FloatField(null=True)),
                ('PS2_time', models.FloatField(null=True)),
                ('high12_time', models.IntegerField(null=True)),
                ('high3_time', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'lesson',
            },
        ),
        migrations.CreateModel(
            name='RegisterWorkReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_name', models.CharField(max_length=20)),
                ('day', models.DateField(null=True)),
                ('student1_1', models.CharField(max_length=20, null=True)),
                ('student1_2', models.CharField(max_length=20, null=True)),
                ('student2_1', models.CharField(max_length=20, null=True)),
                ('student2_2', models.CharField(max_length=20, null=True)),
                ('student3_1', models.CharField(max_length=20, null=True)),
                ('student3_2', models.CharField(max_length=20, null=True)),
                ('student4_1', models.CharField(max_length=20, null=True)),
                ('student4_2', models.CharField(max_length=20, null=True)),
                ('class_time', models.FloatField(null=True)),
                ('PS2_time', models.FloatField(null=True)),
                ('high12_time', models.IntegerField(null=True)),
                ('high3_time', models.IntegerField(null=True)),
                ('unit_test', models.IntegerField(null=True)),
                ('test_review', models.IntegerField(null=True)),
                ('others', models.FloatField(null=True)),
            ],
            options={
                'db_table': 'work_report',
            },
        ),
        migrations.CreateModel(
            name='Teachers',
            fields=[
                ('teacher_id', models.IntegerField(primary_key=True, serialize=False)),
                ('teacher_name', models.CharField(max_length=20)),
                ('fare', models.IntegerField()),
                ('Jan_salary', models.FloatField(default=0)),
                ('Feb_salary', models.FloatField(default=0)),
                ('Mar_salary', models.FloatField(default=0)),
                ('Apr_salary', models.FloatField(default=0)),
                ('May_salary', models.FloatField(default=0)),
                ('Jun_salary', models.FloatField(default=0)),
                ('Jul_salary', models.FloatField(default=0)),
                ('Aug_salary', models.FloatField(default=0)),
                ('Sep_salary', models.FloatField(default=0)),
                ('Oct_salary', models.FloatField(default=0)),
                ('Nov_salary', models.FloatField(default=0)),
                ('Dec_salary', models.FloatField(default=0)),
            ],
            options={
                'db_table': 'teachers',
            },
        ),
    ]
