# Generated by Django 4.1 on 2023-09-27 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teachers',
            fields=[
                ('teacher_id', models.IntegerField(primary_key=True, serialize=False)),
                ('teacher_name', models.CharField(max_length=20)),
                ('fare', models.IntegerField()),
                ('Jan_salary', models.FloatField(default=0)),
                ('Feb_salary', models.FloatField(default=0)),
                ('Mar_salary', models.FloatField(default=0)),
                ('Apr_salary', models.FloatField(default=0)),
                ('May_salary', models.FloatField(default=0)),
                ('Jun_salary', models.FloatField(default=0)),
                ('Jul_salary', models.FloatField(default=0)),
                ('Aug_salary', models.FloatField(default=0)),
                ('Sep_salary', models.FloatField(default=0)),
                ('Oct_salary', models.FloatField(default=0)),
                ('Nov_salary', models.FloatField(default=0)),
                ('Dec_salary', models.FloatField(default=0)),
            ],
            options={
                'db_table': 'teachers',
            },
        ),
    ]
