# Generated by Django 4.1 on 2023-10-19 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PayrollApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='month',
            table='month',
        ),
    ]
