# Generated by Django 4.1 on 2023-09-29 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PayrollApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='registerlesson',
            table='lesson',
        ),
    ]
