# Generated by Django 4.1 on 2023-09-27 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PayrollApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DayOfWeek',
            fields=[
                ('day_id', models.IntegerField(primary_key=True, serialize=False)),
                ('day_name', models.CharField(max_length=5)),
            ],
            options={
                'db_table': 'day_of_week',
            },
        ),
    ]
