# Generated by Django 4.1 on 2023-09-29 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PayrollApp', '0002_alter_registerlesson_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegisterWorkReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_name', models.CharField(max_length=20)),
                ('day', models.DateField(null=True)),
                ('student1_1', models.CharField(max_length=20, null=True)),
                ('student1_2', models.CharField(max_length=20, null=True)),
                ('student2_1', models.CharField(max_length=20, null=True)),
                ('student2_2', models.CharField(max_length=20, null=True)),
                ('student3_1', models.CharField(max_length=20, null=True)),
                ('student3_2', models.CharField(max_length=20, null=True)),
                ('student4_1', models.CharField(max_length=20, null=True)),
                ('student4_2', models.CharField(max_length=20, null=True)),
                ('class_time', models.FloatField(null=True)),
                ('PS2_time', models.FloatField(null=True)),
                ('high12_time', models.IntegerField(null=True)),
                ('high3_time', models.IntegerField(null=True)),
                ('unit_test', models.IntegerField(null=True)),
                ('test_review', models.IntegerField(null=True)),
                ('others', models.FloatField(null=True)),
            ],
            options={
                'db_table': 'work_report',
            },
        ),
    ]
