# Generated by Django 4.1 on 2023-10-19 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PayrollApp', '0002_alter_month_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registerlesson',
            name='PS2_time',
        ),
        migrations.RemoveField(
            model_name='registerlesson',
            name='class_time',
        ),
        migrations.RemoveField(
            model_name='registerlesson',
            name='day_of_week',
        ),
        migrations.RemoveField(
            model_name='registerlesson',
            name='high12_time',
        ),
        migrations.RemoveField(
            model_name='registerlesson',
            name='high3_time',
        ),
        migrations.RemoveField(
            model_name='registerlesson',
            name='student1_1',
        ),
        migrations.RemoveField(
            model_name='registerlesson',
            name='student1_2',
        ),
        migrations.RemoveField(
            model_name='registerlesson',
            name='student2_1',
        ),
        migrations.RemoveField(
            model_name='registerlesson',
            name='student2_2',
        ),
        migrations.RemoveField(
            model_name='registerlesson',
            name='student3_1',
        ),
        migrations.RemoveField(
            model_name='registerlesson',
            name='student3_2',
        ),
        migrations.RemoveField(
            model_name='registerlesson',
            name='student4_1',
        ),
        migrations.RemoveField(
            model_name='registerlesson',
            name='student4_2',
        ),
        migrations.RemoveField(
            model_name='registerlesson',
            name='teacher_name',
        ),
    ]
