# Generated by Django 4.1 on 2023-10-19 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PayrollApp', '0003_remove_registerlesson_ps2_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registerlesson',
            name='PS2_time',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='registerlesson',
            name='class_time',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='registerlesson',
            name='day_of_week',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='registerlesson',
            name='high12_time',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='registerlesson',
            name='high3_time',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='registerlesson',
            name='student1_1',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='registerlesson',
            name='student1_2',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='registerlesson',
            name='student2_1',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='registerlesson',
            name='student2_2',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='registerlesson',
            name='student3_1',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='registerlesson',
            name='student3_2',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='registerlesson',
            name='student4_1',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='registerlesson',
            name='student4_2',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='registerlesson',
            name='teacher_name',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
