# Generated by Django 4.1 on 2023-10-05 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PayrollApp', '0003_registerworkreport'),
    ]

    operations = [
        migrations.CreateModel(
            name='Month',
            fields=[
                ('month_id', models.IntegerField(primary_key=True, serialize=False)),
                ('month', models.IntegerField()),
            ],
        ),
    ]
