# Generated by Django 4.1 on 2023-10-05 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PayrollApp', '0004_month'),
    ]

    operations = [
        migrations.AlterField(
            model_name='month',
            name='month',
            field=models.CharField(max_length=5),
        ),
    ]
