# Generated by Django 4.1 on 2023-10-19 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PayrollApp', '0004_registerlesson_ps2_time_registerlesson_class_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registerlesson',
            name='day',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='registerworkreport',
            name='day_of_week',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='registerworkreport',
            name='teacher_name',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
