# Generated by Django 4.1 on 2023-10-25 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PayrollApp', '0005_registerlesson_day_registerworkreport_day_of_week_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CSV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_name', models.CharField(max_length=20)),
                ('month', models.CharField(max_length=5)),
            ],
            options={
                'db_table': 'csv',
            },
        ),
    ]
